version: '3'

services:
  # Servicio de la aplicación
  app:
    image: integracion:latest
    ports:
      - "3333:3333"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=T5iHduLMtUMVyQ0TyWhrYTQHRcH9Oz7j
      - DRIVE_DISK=local
      - DB_CONNECTION=sybase
      - SYBASE_HOST=192.168.100.37
      - SYBASE_PORT=2638
      - SYBASE_USER=DBA
      - SYBASE_PASSWORD=ownlomas1415key
      - SYBASE_SERVERNAME=integrado
      - SESSION_DRIVER=cookie
      - CACHE_VIEWS=false
      - MYSQL_HOST=192.168.100.37
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB_NAME=prueba
      # - DEBUG=knex*
      - DEBUG=false

    # environment:
    #   - NODE_ENV=pro  # o dev según el entorno
    # depends_on:
    #   - integrado
    #   - mysql

  # # Servicio de la base de datos SQL Anywhere
  # integrado:
  #  image: ivangco/sybase 
  #  ports:
  #   - "2638:2638"

  # # Servicio de la base de datos MySQL
  # mysql:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=prueba
  #     # - MYSQL_USER=root
  #     # - MYSQL_PASSWORD=root
  #   command: --default-authentication-plugin=caching_sha2_password
  #   ports:
  #     - "3306:3306"
  #   # volumes:
  #   #   - ./mysql_data:/var/lib/mysql
      
 
